# Generated by Django 5.2.8 on 2026-02-11 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
        ('registro', '0002_aprendiz_codigo_expiracion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha_publicacion',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='registro.bienestar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(choices=[('salud', 'Salud'), ('bienestar', 'Bienestar'), ('evento', 'Evento'), ('informacion', 'Información General'), ('otro', 'Otro')], default='informacion', max_length=20),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ArchivoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('archivo', models.FileField(upload_to='publicaciones/%Y/%m/%d/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='publicaciones.publicacion')),
            ],
            options={
                'verbose_name': 'Archivo de Publicación',
                'verbose_name_plural': 'Archivos de Publicaciones',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.bienestar')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='publicaciones.publicacion')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='publicaciones.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.bienestar')),
            ],
            options={
                'verbose_name': 'Me gusta',
                'verbose_name_plural': 'Me gusta',
                'unique_together': {('usuario', 'publicacion')},
            },
        ),
    ]
