# Generated by Django 5.2.8 on 2026-02-03 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha_publicacion',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='registro.bienestar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(choices=[('salud', 'Salud'), ('bienestar', 'Bienestar'), ('evento', 'Evento'), ('informacion', 'Información General'), ('otro', 'Otro')], default='informacion', max_length=20),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
