# Generated by Django 5.2.8 on 2026-02-13 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_alter_publicacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivopublicacion',
            name='publicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='publicaciones.publicacion'),
            preserve_default=False,
        ),
    ]
