# Generated by Django 5.2.8 on 2026-02-03 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='fecha',
            new_name='creado',
        ),
    ]
