# Generated by Django 5.2.8 on 2026-02-03 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_rename_fecha_like_creado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['creado']},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='texto',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha',
            new_name='creado',
        ),
    ]
