# Generated by Django 5.2.8 on 2026-02-03 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion'),
        ),
    ]
