# Generated by Django 5.2.8 on 2025-11-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aprendiz', 'Aprendiz'), ('instructor', 'Instructor'), ('bienestar', 'Bienestar')], max_length=20)),
                ('documento', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfils/')),
            ],
            options={
                'db_table': 'usuario_unificado',
            },
        ),
    ]
