# info/settings.py
"""
Django settings for info project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import pymysql
pymysql.install_as_MySQLdb()

# Cargar variables de entorno desde .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # QUÉDATE CON ESTA

# Static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files
import cloudinary

# Cloudinary
cloudinary.config(
    cloud_name=os.getenv('CLOUDINARY_CLOUD_NAME'),
    api_key=os.getenv('CLOUDINARY_API_KEY'),
    api_secret=os.getenv('CLOUDINARY_API_SECRET'),
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY':    os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
    'MEDIA_TAG': 'media',
    'STATIC_TAG': 'static',
    'STATIC_IMAGES_EXTENSIONS': ['jpg', 'jpe', 'jpeg', 'png', 'gif', 'webp', 'bmp'],
    'STATIC_VIDEOS_EXTENSIONS': ['mp4', 'webm', 'flv', 'mov', 'ogv', 'avi', 'wmv'],
}

# Media files
MEDIA_URL = '/media/'

if os.getenv('CLOUDINARY_CLOUD_NAME'):
    STORAGES = {
        "default": {
            "BACKEND": "utils.storage.MediaOrVideoCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-h2*$b!#5upbewe)h)c0s074)!675xs#zj4sj$sx3yd*bn55k!1')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')
if '127.0.0.1' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('127.0.0.1')
if '' in ALLOWED_HOSTS:
    ALLOWED_HOSTS.remove('')

# Necesario para que Django detecte HTTPS detrás del proxy de Railway
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF trusted origins para producción
CSRF_TRUSTED_ORIGINS = [
    'https://*.up.railway.app',
    'https://web-production-6b79c.up.railway.app',
]
_csrf_extra = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if _csrf_extra:
    for _origin in _csrf_extra.split(','):
        _origin = _origin.strip()
        if _origin and _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_origin)
for _host in ALLOWED_HOSTS:
    _host = _host.strip()
    if _host and _host not in ('127.0.0.1', 'localhost'):
        for _scheme in ('https://', 'http://'):
            _o = f'{_scheme}{_host}'
            if _o not in CSRF_TRUSTED_ORIGINS:
                CSRF_TRUSTED_ORIGINS.append(_o)


# Application definitionwww

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary',
    'django.contrib.staticfiles',

    'applications.registro.apps.IndexConfig',
    'applications.sesion',
    'applications.index',
    'applications.usuarios',
    'applications.moderacion',
    'applications.publicaciones',
    'applications.amistades',
    'applications.chat',
    'applications.perfil',
    'applications.notificaciones',
    'applications.busqueda',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'applications.sesion.middleware.NoCacheMiddleware',
]

ROOT_URLCONF = 'info.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'info.wsgi.application'
ASGI_APPLICATION = 'info.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [os.getenv('REDIS_URL', 'redis://127.0.0.1:6379')],
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------------------
# CONFIGURACIÓN DE CORREO (RECUPERAR CONTRASEÑA)
# ------------------------------------------

#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#EMAIL_HOST = "smtp.gmail.com"
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
#EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'perezpolancocarlosmario@gmail.com')
#EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'zdotpwzoijuwwsts')


RESEND_API_KEY = os.getenv('RESEND_API_KEY')
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER', 'onboarding@resend.dev')
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', 'perezpolancocarlosmario@gmail.com')

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
PERSPECTIVE_API_KEY = os.getenv('PERSPECTIVE_API_KEY', 'AIzaSyClFIfrYfiMOtH3nDTgBtYNSxS08en0fH4')
PERSPECTIVE_DEBUG = True
# Modelo de moderación
OPENAI_MODERATION_MODEL = 'omni-moderation-latest'

PERSPECTIVE_THRESHOLDS = {
    'TOXICITY': 0.5,          # Toxicidad general (recomendado: 0.6-0.8)
    'SEVERE_TOXICITY': 0.4,   # Toxicidad severa (recomendado: 0.5-0.7)
    'INSULT': 0.5,            # Insultos directos (recomendado: 0.6-0.8)
    'PROFANITY': 0.5,         # Groserías/palabrotas (recomendado: 0.6-0.8)
    'THREAT': 0.4,            # Amenazas (recomendado: 0.5-0.7)
    'IDENTITY_ATTACK': 0.5,   # Ataques por identidad (recomendado: 0.6-0.8)
}

# Configuración de moderación
MODERACION_CACHE_TIMEOUT = 300
MODERACION_RATE_LIMIT_DELAY = 2  # 2 segundos entre peticiones (NUEVO)
MODERACION_MAX_RETRIES = 3  # Reintentos en caso de error (NUEVO)
MODERACION_RETRY_DELAY = 5  # Espera 5 segundos antes de reintentar (NUEVO)

# 4. Comportamiento cuando falla la API
MODERACION_FALLBACK_MODE = 'permisivo'
MODERACION_MAX_TEXTO_LENGTH = 5000
MODERACION_MAX_IMAGE_SIZE = 10 * 1024 * 1024  # 10MB
MODERACION_MAX_VIDEO_SIZE = 50 * 1024 * 1024  # 50MB

# Categorías bloqueadas
MODERACION_CATEGORIAS_BLOQUEADAS = [
    'sexual', 'sexual/minors', 'violence', 'violence/graphic',
    'harassment', 'harassment/threatening', 'hate', 'hate/threatening',
    'self-harm', 'self-harm/intent', 'self-harm/instructions',
    'illicit', 'illicit/violent'
]

# Palabras prohibidas (personaliza según tu región)
MODERACION_PALABRAS_PROHIBIDAS = [
    'puta', 'puto', 'mierda', 'verga', 'pendejo',
    'gonorrea', 'hijueputa', 'malparido', 'marica',
    'maricon', 'cabron', 'imbecil', 'estupido', 'pito',
    'pene', 'tetas', 'cuca', 'vagina', 'culo', 'tetranutra',
    'cacorro', 'sapo', 'zunga', 'valija', 'pirobo', 'pingo',
    'pato', 'pata', 'mamerto', 'lanpara', 'guisa', 'guaricha',
            # Abreviaciones
    'hp', 'hdp', 'mrda', 'pndj', 'pt', 'pto', 'pta', 'hpta', 'mka', 'mrka', 'mrd',
    'hpt', 'mk', 'pm'
]

# Caché (opcional pero recomendado)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}
  # ← IMPORTANTE
MODERACION_RATE_LIMIT_DELAY = 3  # 2 segundos entre peticiones