# Generated by Django 5.2.8 on 2026-02-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabraProhibida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100, unique=True)),
                ('severidad', models.IntegerField(default=1, help_text='1=Leve, 2=Moderado, 3=Severo, 4=Crítico')),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Palabra Prohibida',
                'verbose_name_plural': 'Palabras Prohibidas',
                'db_table': 'palabras_prohibidas',
                'ordering': ['-severidad', 'palabra'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioSancionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sancion', models.CharField(choices=[('advertencia', 'Advertencia'), ('suspension_temporal', 'Suspensión Temporal'), ('baneo_permanente', 'Baneo Permanente')], max_length=30)),
                ('razon', models.TextField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('aplicada_por', models.CharField(default='sistema_automatico', max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Usuario Sancionado',
                'verbose_name_plural': 'Usuarios Sancionados',
                'db_table': 'usuarios_sancionados',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroModeracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contenido', models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('video', 'Video'), ('archivo', 'Archivo')], max_length=20)),
                ('resultado', models.CharField(choices=[('aprobado', 'Aprobado'), ('bloqueado', 'Bloqueado'), ('error', 'Error')], max_length=20)),
                ('contenido_texto', models.TextField(blank=True, null=True)),
                ('archivo_url', models.URLField(blank=True, null=True)),
                ('razon', models.TextField()),
                ('categorias_violadas', models.JSONField(blank=True, default=list)),
                ('score_confianza', models.JSONField(blank=True, default=dict)),
                ('metodo_usado', models.CharField(default='openai_api', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderaciones', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Registro de Moderación',
                'verbose_name_plural': 'Registros de Moderación',
                'db_table': 'registros_moderacion',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['-creado_en'], name='registros_m_creado__eb7b3b_idx'), models.Index(fields=['usuario', '-creado_en'], name='registros_m_usuario_69873c_idx'), models.Index(fields=['resultado'], name='registros_m_resulta_0405d2_idx')],
            },
        ),
    ]
