# Generated by Django 5.2.8 on 2025-12-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group', models.BooleanField(default=False)),
                ('nombre_grupo', models.CharField(blank=True, max_length=150, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('participantes', models.ManyToManyField(related_name='chats', to='usuarios.usuario')),
            ],
        ),
    ]
