# Generated by Django 5.2.8 on 2026-02-11 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-actualizado_en'], 'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='creado',
            new_name='creado_en',
        ),
        migrations.AddField(
            model_name='chat',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='admin_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_admin', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='chat',
            name='descripcion_grupo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='foto_grupo',
            field=models.ImageField(blank=True, null=True, upload_to='grupos/'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='Es grupo'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='nombre_grupo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='participantes',
            field=models.ManyToManyField(related_name='chats', to='usuarios.usuario', verbose_name='Participantes'),
        ),
        migrations.AlterModelTable(
            name='chat',
            table='chats',
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('enviado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(blank=True, null=True)),
                ('visto', models.BooleanField(default=False)),
                ('visto_en', models.DateTimeField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='mensajes/')),
                ('tipo_archivo', models.CharField(blank=True, max_length=20, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='usuarios.usuario')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat.chat')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'mensajes',
                'ordering': ['enviado'],
            },
        ),
        migrations.CreateModel(
            name='MensajeVisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto_en', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistos_por', to='chat.mensaje')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Mensaje Visto',
                'verbose_name_plural': 'Mensajes Vistos',
                'db_table': 'mensajes_vistos',
                'unique_together': {('mensaje', 'usuario')},
            },
        ),
    ]
