# Generated by Django 5.2.8 on 2026-03-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='nombre_archivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='tamanio_archivo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
