# Generated by Django 5.2.8 on 2026-03-03 18:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_mensaje_nombre_archivo_mensaje_tamanio_archivo'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='vaciado_para',
            field=models.ManyToManyField(blank=True, related_name='chats_vaciados', to='usuarios.usuario', verbose_name='Vaciado para'),
        ),
        migrations.CreateModel(
            name='ChatVaciadoPorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaciado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaciados_por', to='chat.chat')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_vaciados_registros', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Chat Vaciado por Usuario',
                'db_table': 'chat_vaciado_por_usuario',
                'unique_together': {('chat', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='MensajeEliminadoParaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado_en', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_para', to='chat.mensaje')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_eliminados', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Mensaje Eliminado para Usuario',
                'db_table': 'mensaje_eliminado_para_usuario',
                'unique_together': {('mensaje', 'usuario')},
            },
        ),
    ]
