# Generated by Django 5.2.8 on 2026-02-04 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('publicaciones', '0008_alter_like_publicacion'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='receptor',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='url',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destinatario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacion',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='emisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('solicitud_amistad', 'Solicitud de amistad'), ('amistad_aceptada', 'Amistad aceptada'), ('nueva_publicacion', 'Nueva publicación'), ('comentario', 'Nuevo comentario'), ('like', 'Le gustó tu publicación')], max_length=30),
        ),
    ]
