# Generated by Django 5.2.8 on 2026-02-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('solicitud_amistad', 'Solicitud de amistad'), ('amistad_aceptada', 'Amistad aceptada'), ('nueva_publicacion', 'Nueva publicación'), ('comentario', 'Nuevo comentario'), ('like', 'Le gustó tu publicación'), ('mensaje', 'Nuevo mensaje')], max_length=30),
        ),
    ]
