# Generated by Django 5.2.8 on 2026-03-03 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_alter_notificacion_tipo'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSilenciado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silenciado_en', models.DateTimeField(auto_now_add=True)),
                ('silenciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silenciado_por', to='usuarios.usuario', verbose_name='Usuario silenciado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_silenciados', to='usuarios.usuario', verbose_name='Usuario que silencia')),
            ],
            options={
                'verbose_name': 'Chat Silenciado',
                'verbose_name_plural': 'Chats Silenciados',
                'db_table': 'chat_silenciado',
                'unique_together': {('usuario', 'silenciado')},
            },
        ),
    ]
