# Generated by Django 5.2.8 on 2026-02-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('numero_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('centro_formativo', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=100)),
                ('jornada', models.CharField(max_length=50)),
                ('ficha', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/aprendices/')),
                ('verificado', models.BooleanField(default=False)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=6, null=True)),
                ('codigo_expiracion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aprendiz',
            },
        ),
        migrations.CreateModel(
            name='Bienestar',
            fields=[
                ('numero_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('centro_formativo', models.CharField(default='Centro desconocido', max_length=150)),
                ('region', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/bienestar/')),
                ('verificado', models.BooleanField(default=False)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=6, null=True)),
                ('codigo_expiracion', models.DateTimeField(blank=True, null=True)),
                ('verificado_admin', models.BooleanField(default=False)),
                ('codigo_admin', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'bienestar',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('numero_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('centro_formativo', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/instructores/')),
                ('verificado', models.BooleanField(default=False)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=6, null=True)),
                ('codigo_expiracion', models.DateTimeField(blank=True, null=True)),
                ('verificado_admin', models.BooleanField(default=False)),
                ('codigo_admin', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
    ]
