# Generated by Django 5.2.8 on 2025-12-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='perfiles/default.jpg', null=True, upload_to='perfiles/aprendices/'),
        ),
        migrations.AddField(
            model_name='bienestar',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='perfiles/default.jpg', null=True, upload_to='perfiles/aprendices/'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='perfiles/default.jpg', null=True, upload_to='perfiles/aprendices/'),
        ),
    ]
