# Generated by Django 5.2.8 on 2025-12-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_aprendiz_foto_perfil_bienestar_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/aprendices/'),
        ),
        migrations.AlterField(
            model_name='bienestar',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/aprendices/'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/aprendices/'),
        ),
    ]
