# Generated by Django 5.2.8 on 2025-12-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_aprendiz_foto_perfil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprendiz',
            old_name='foto_perfil',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='bienestar',
            old_name='foto_perfil',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='foto_perfil',
            new_name='foto',
        ),
    ]
