# Generated by Django 5.2.8 on 2026-03-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacidadPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(db_index=True, max_length=30, unique=True)),
                ('mostrar_email', models.BooleanField(default=True)),
                ('mostrar_documento', models.BooleanField(default=True)),
                ('mostrar_centro', models.BooleanField(default=True)),
                ('mostrar_region', models.BooleanField(default=True)),
                ('mostrar_ficha', models.BooleanField(default=True)),
                ('mostrar_jornada', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Privacidad de perfil',
                'verbose_name_plural': 'Privacidades de perfil',
            },
        ),
    ]
