# Generated by Django 5.2.8 on 2025-12-09 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienestar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Aprendiz',
        ),
        migrations.DeleteModel(
            name='Bienestar',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
